version: '3.8'
services:
  api:
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=4000
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=project_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
